### ISSUE TITLE
TODOs diversos do TabNews

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/tabnews.com.br#164]
Turma, tudo bem? Vou começar a juntar aqui alguns afazeres de manutenção geral do TabNews. Quem quiser participar será super bem vindo e serão uma ótima oportunidade para rodar o projeto na máquina e fazer alguma alteração 🤝 

A lista naturalmente vai começar pequena, mas vou juntando aqui os itens 👍 

# Reorganizar o nome dos jobs na Action do Github
- [x] **Feito por @andrefd17 no #165**

Hoje quando roda alguma action, o resultado está assim:

![image](https://user-images.githubusercontent.com/4248081/151264046-531cf94c-5f69-4d09-adc9-320b29fbdb34.png)

Os nomes estão um pouco redundantes, seria legal deixar mais simples, por exemplo:

```
CI / Tests (pull_request)
CI / Lint Styles (pull_request)
CI / Lint Commits (pull_request)
```

# Reduzir o tempo do Build

- [ ] **Feito**

Olha só que interessante, nos testes automatizados, o comando que mais demora **(1m32s)** é o build do `next` pelo comando `npm run build`:

![image](https://user-images.githubusercontent.com/4248081/151264406-f00589f0-26ce-41ac-9705-cb7f035aa866.png)

Eu especulo que isso esteja acontecendo porque ao invés de colocarmos as imagens no `/public` e chamar elas na página de uma forma tradicional, a gente processa elas de forma dinâmica por aquele recurso novo lá que manda pra CDN e otimiza tudo usando o componente `<Image>`.

Sugiro remover isso, hospedar e chamar as imagens tradicionalmente, para ver se isso contribui na velocidade do build.

# Usar SWC para acelerar desenvolvimento e build

- [x] **Feito no #173 mas não teve efeito esperado, então não foi merged**

O @andrefd17 notou que não estamos usando o novo `SWC`, que é um novo compilador feito em Rust e que acelera muito a compilação de JavaScript. Ele não está sendo usado, pois temos um `.babelrc` customizado. Podemos investigar o que ele faz e o que acontece se tirar.

![image](https://user-images.githubusercontent.com/4248081/151268894-ffdb92c4-d3ce-4f76-9bd4-5a3699b8b031.png)

# Usar cache do Actions no build

- [x] **Feito por @andrefd17 no #167**

Utilizar o próprio recurso de cache do Github Actions.
