### ISSUE TITLE
Refazer todo o Sistema de Validação

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/tabnews.com.br#236]
## Contexto

Estou zero satisfeito em como estamos lidando com validação hoje no projeto, tanto por ter coisas duplicadas que não deveriam estar duplicadas, quanto vários rombos na interface e que não validam coisas como o que é enviado em `query` parameters, apenas é validado o que é enviado no `body`. Esse susto veio depois de uma conversa com o Andres Alonso do The Bug Hunter e numa parte específica do curso dele sobre **IDOR (Insecure Direct Object Reference)** como que isso facilmente pode se tornar um problema gravíssimo. Eu sinceramente tomei um susto com que várias empresas grandes caíram em problemas assim.

Validar parâmetros não necessariamente evita problemas de IDOR, mas são problemas causados pela mesma superfície, então você precisa tratar ela de todos os ângulos e essa issue é sobre dois ângulos que vou explorar na próxima seção.

## Execução

Sugiro implementar no sistema dois tipos de validação:

1. Validação sintética
2. Validação de negócio

### 1. Validação sintética
Eu não sei se o primeiro nome está certo, mas é o tipo de validação que não tem regra de negócio a não ser validar que o campo enviado está de acordo com as regras. E devemos fazer isso nas bordas do nosso sistema, onde no nosso caso é fazer nos Controllers da API.

Um exemplo disso é validar que o campo `password` é uma string e possui limite mínimo e máximo de X caracteres. Ou então se o `password` e `password_confirmation` são iguais, isso também pode ser feito nessa camada.

No final das contas o principal trabalho dela é evitar que **lixo** seja passado para outras camadas do sistema.

Hoje o sistema faz isso, tanto nos filtros de input, quanto em camadas mais internas, como por exemplo aqui:

https://github.com/filipedeschamps/tabnews.com.br/blob/a9245ce3abe6b4b4f941a7008498b6cb96e733ed/models/user.js#L105-L113

O que já logo em baixo gera quase que uma duplicação, pois nesse caso não é `required`:

https://github.com/filipedeschamps/tabnews.com.br/blob/a9245ce3abe6b4b4f941a7008498b6cb96e733ed/models/user.js#L193-L199

Então mais abaixo eu sugiro uma ideia de como não ter uma parte dessa repetição.

### 2. Validação de negócio

Depois disso entram as regras de negócio e isso são validações que estão em camadas mais profundas do sistema, por exemplo dentro dos models.

Um exemplo é não conseguir ativar um usuário que já está ativo. Esse caso em específico começa nessa função:

https://github.com/filipedeschamps/tabnews.com.br/blob/a9245ce3abe6b4b4f941a7008498b6cb96e733ed/pages/api/v1/activate/%5Btoken%5D.public.js#L20

E você pode passar alguém que já teve a feature `read:activation_token` removida, pois isso vai ser pego aqui:

https://github.com/filipedeschamps/tabnews.com.br/blob/a9245ce3abe6b4b4f941a7008498b6cb96e733ed/models/activation.js#L88-L98

### Conclusão

Dado a isso, sugiro centralizarmos a validação, pelo menos a relação entre campo e o que esperar dele.

Sou novo no mundo do JOI, mas ele parece oferecer algumas opções para construir schemas de formas dinâmicas, onde eu declaro parâmetros soltos em um lugar e uso isso em outros lugares. Não sei muito bem como fazer para hora um parâmetro ser required, outra hora não, e usando todas as mesmas mensagens, mas não estou longe de descobrir como fazer. Vou deixar abaixo alguns links de uma pesquisa que fiz:

Esse link mostra como usar contextos, e talvez passar ali que algo é required ou não:
https://github.com/sideway/joi/issues/1683#issuecomment-446647506

```js
const schema = Joi.object().keys({
    conditional: Joi.number().when('$condition', {
        is: Joi.boolean().valid(true).required(),
        then: Joi.required(),
        otherwise: Joi.optional()
    })
});

schema.validate({}); // error: null
schema.validate({}, {context: {condition: false}}); // error: null
schema.validate({}, {context: {condition: true}}); // ValidationError: child "conditional" fails because ["conditional" is required]
```

---

Esse outro link mostra como declarar campos singulares, e depois juntar tudo:
https://stackoverflow.com/a/63221642

**Declarando os campos de forma isolada:**

```js
//an email address
  static emailAddress = Joi.object({
    emailAddress: Joi.string()
      .email({ tlds: { allow: false } })
      .required()
      .label("Email Address"),
  });

  static passwordRegex = /^(?=.*[A-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%^&*()])\S{8,}$/;
  static passwordError =
    "Password must be at least 8 characters long, and have at least one uppercase letter, one lowercase letter, one number, and one special character.";
  
  //a password
  static password = Joi.object({
    password: Joi.string()
      .min(8)
      .regex(this.passwordRegex)
      .message(this.passwordError)
      .label("Password"),
  });
```

**Montando o Schema final**

```js
static registerUserSchema() {
    let schema = Joi.object()
      .concat(this.yourNameSchema)
      .concat(this.emailAddress)
      .concat(this.password)
      .concat(this.confirmPassword);
    return schema;
  }
```

---

Outro exemplo mostrando como fazer required condicional (não lembro de onde tirei):

```js
let externalVar = true

module.exports = Joi.object({
  username: Joi.string().alphanum().min(3).max(30).required(),
  password: Joi.string().pattern( /^[a-zA-Z0-9]{3,30}$/ ).required(),

  // here
  role: Joi.number().when(externalVar, { is: false, then: Joi.required(), otherwise: null })
})
```

## Conclusão

Essa issue acabou trazendo muitas coisas importantes para o projeto, segue a lista:

- [x] Criar módulo e aplicar nos primeiros casos
- [x] Mover testes para novo padrão
- [x] Aplicação desse módulo em todo resto da aplicação
- [x] Renomear parâmetros na resposta para Snake case: "request_id", "error_id" e "error_unique_code" (vou deixar para outro PR)
- [x] Adicionar mais cobertura de testes para cobrir furos anteriores
- [x] Validar Headers (o formato e caracteres aceitos no Cookie de Sessão "session_id")
- [x] Não relacionado, mas vou deixar anotado aqui para não esquecer: O novo Logger que usa PinoJS está sofrendo algum leak, o mesmo [reportado aqui](https://github.com/pinojs/pino/issues/1322)
- [x] Também não relacionado, mas importante para segurança atual: não deixar usuário atualizar email e senha, até que seja implementado fluxo de dupla verificação por email.
